apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-testbox
spec:
  podSelector:
    matchLabels:
      app: testbox-deny
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 8080
